### PR TITLE
Add WPF user interface

### PR DESCRIPTION
**Pull request by NoFear23m**

### CODE REVIEW

**Comment by NoFear23m** [comment]
@FireEmerald What do you mean? The PullRequest was merged. ProgTrade has removed the PullRequests which were commented in German. I have made a new one.

**Comment by FireEmerald** [comment]
Your new PR was merged and my comment was posted on it's merge commit https://github.com/ProgTrade/nUpdate/commit/739d66e8750eb7bb3fcafbbbffe867375f7d20e8#diff-dc0a055044eb5af448c99202b394e57eR18.

But after reading some lines of code i think ProgTrade will update these leftovers and other things like this hard coded link: https://github.com/ProgTrade/nUpdate/commit/739d66e8750eb7bb3fcafbbbffe867375f7d20e8#diff-4d8a7f6592ac998f65559397a3634d5eR21

**Comment by NoFear23m** [comment]
The link is in the test project, and as it is still under development we leave the hardcoded link in it until the WPF UI is complete. But thanks for your reference. I will also make some changes the next days.

**Comment by ProgTrade** [comment]
Yes, as @NoFear23m said, these leftovers will be handled later. Additionally, the test project is only used for internal purposes and so the hardcoded parts do not disturb the functionality. But, we will make that more dynamic, too.

We‘ve now splitted the previous functionality commits into two pull requests to make this more transparent. The update condition request will be created today. There were some problems with git, that‘s not why.

The plan is to implement these features basically, now. We still have to change the architecture later and there we are able to cleanup everything. At the moment, that is no problem. It‘s what the develop-v3-branch is for as it does not interfere with master.

**Pull request merged**
